version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_random_secret_here
      - MONGODB_URI=mongodb://localhost:27017/budgetapp
      - REACT_APP_API_URL=http://localhost:5001
  frontend:
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
