version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/budgetapp
  frontend:
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
